#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


a0 = 1
a1 = 1
a2 = 2
fib = list()
while a1 < 4000000:
   a0 = a1
   a1 = a2
   a2 = a1 + a0
   if a0 % 2 == 0:
      fib.append(a0)
	  
print sum(fib)
